name: Reward closed issue

on:
  pull_request_target:
    types: [closed]
    branches:
      - main
    # Only run when pull request is merged
    # (optional, as closing a pull request for other reasons will also trigger this)
    conditions:
      - github.event.action == 'closed'
      - github.event.pull_request.merged == true

jobs:
  run-python-script:
    name: Reward closed issue
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run Python script
        run: python .github/scripts/reward.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_FULL_NAME: ${{ github.event.repository.full_name }}
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
